version: 0.0
os: linux
files:
  - source: user-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user
  - source: before_install.sh
    destination: /home/ec2-user
  - source: application_start.sh
    destination: /home/ec2-user

permissions:
  - object: user-0.0.1-SNAPSHOT.jar
    mode: "755"
    owner: ec2-user
    group: ec2-user
  - object: before_install.sh
    mode: "755"
    owner: ec2-user
    group: ec2-user
  - object: application_start.sh
    mode: "755"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ec2-user
