package com.user.adapter

import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.test.context.ActiveProfiles

@SpringBootConfiguration
@SpringBootApplication
class AdapterTestConfiguration