name: dayplan-user
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests and Build
        run: ./gradlew build --info

      - name: Archive deployment files
        run: |

          cp build/libs/user-0.0.1-SNAPSHOT.jar ./
          cp deploy/application_start.sh ./
          cp deploy/before_install.sh ./
          cp deploy/appspec.yml ./

          tar -cvf dayplan-user-app.tar \
            user-0.0.1-SNAPSHOT.jar \
            application_start.sh \
            before_install.sh \
            appspec.yml

          rm user-0.0.1-SNAPSHOT.jar application_start.sh before_install.sh appspec.yml

      - name: Upload TAR to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            dayplan-user-app.tar s3://dayplan/dayplan-user-app.tar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true

      - name: Deploy using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name Dayplan-User-Deploy \
            --deployment-group-name Dayplan-User \
            --s3-location bucket=dayplan,bundleType=tar,key=dayplan-user-app.tar
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

