#name: Run Tests on PR to main
#
#on:
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  test:
#    runs-on: ubuntu-20.04
#
#    services:
#      redis:
#        image: redis
#        ports:
#          - 6379:6379
#        options: --entrypoint redis-server
#
#    steps:
#      - name: Checkout source code.
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Run Tests
#        run: ./gradlew test
